{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "fbdd0753",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "zsh:1: command not found: apt-get\n",
      "zsh:1: command not found: apt-get\n",
      "zsh:1: command not found: wget\n",
      "zsh:1: command not found: wget\n",
      "tar: Error opening archive: Failed to open 'spark-3.2.0-bin-hadoop2.7.tgz'\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/juliabecker/opt/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_62307411b05142fea3f5b376c1745eb1/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_62307411b05142fea3f5b376c1745eb1/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-pip-egg-info-52mukwjv\n",
      "         cwd: /private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_62307411b05142fea3f5b376c1745eb1/\n",
      "    Complete output (15 lines):\n",
      "    /bin/sh: mysql_config: command not found\n",
      "    /bin/sh: mariadb_config: command not found\n",
      "    /bin/sh: mysql_config: command not found\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_62307411b05142fea3f5b376c1745eb1/setup.py\", line 15, in <module>\n",
      "        metadata, options = get_config()\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_62307411b05142fea3f5b376c1745eb1/setup_posix.py\", line 70, in get_config\n",
      "        libs = mysql_config(\"libs\")\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_62307411b05142fea3f5b376c1745eb1/setup_posix.py\", line 31, in mysql_config\n",
      "        raise OSError(\"{} not found\".format(_mysql_config_path))\n",
      "    OSError: mysql_config not found\n",
      "    mysql_config --version\n",
      "    mariadb_config --version\n",
      "    mysql_config --libs\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/de/79/d02be3cb942afda6c99ca207858847572e38146eb73a7c4bfe3bdf154626/mysqlclient-2.1.0.tar.gz#sha256=973235686f1b720536d417bf0a0d39b4ab3d5086b2b6ad5e6752393428c02b12 (from https://pypi.org/simple/mysqlclient/) (requires-python:>=3.5). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/juliabecker/opt/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_f619a636d0b84add913b29802368c447/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_f619a636d0b84add913b29802368c447/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-pip-egg-info-ncrsiyzt\n",
      "         cwd: /private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_f619a636d0b84add913b29802368c447/\n",
      "    Complete output (15 lines):\n",
      "    /bin/sh: mysql_config: command not found\n",
      "    /bin/sh: mariadb_config: command not found\n",
      "    /bin/sh: mysql_config: command not found\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_f619a636d0b84add913b29802368c447/setup.py\", line 15, in <module>\n",
      "        metadata, options = get_config()\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_f619a636d0b84add913b29802368c447/setup_posix.py\", line 70, in get_config\n",
      "        libs = mysql_config(\"libs\")\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_f619a636d0b84add913b29802368c447/setup_posix.py\", line 31, in mysql_config\n",
      "        raise OSError(\"{} not found\".format(_mysql_config_path))\n",
      "    OSError: mysql_config not found\n",
      "    mysql_config --version\n",
      "    mariadb_config --version\n",
      "    mysql_config --libs\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/3c/df/59cd2fa5e48d0804d213bdcb1acb4d08c403b61c7ff7ed4dd4a6a2deb3f7/mysqlclient-2.0.3.tar.gz#sha256=f6ebea7c008f155baeefe16c56cd3ee6239f7a5a9ae42396c2f1860f08a7c432 (from https://pypi.org/simple/mysqlclient/) (requires-python:>=3.5). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/juliabecker/opt/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_2666df71fc7d40ef9e671e18d9093999/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_2666df71fc7d40ef9e671e18d9093999/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-pip-egg-info-u57mky1g\n",
      "         cwd: /private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_2666df71fc7d40ef9e671e18d9093999/\n",
      "    Complete output (12 lines):\n",
      "    /bin/sh: mysql_config: command not found\n",
      "    /bin/sh: mariadb_config: command not found\n",
      "    /bin/sh: mysql_config: command not found\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_2666df71fc7d40ef9e671e18d9093999/setup.py\", line 15, in <module>\n",
      "        metadata, options = get_config()\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_2666df71fc7d40ef9e671e18d9093999/setup_posix.py\", line 65, in get_config\n",
      "        libs = mysql_config(\"libs\")\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_2666df71fc7d40ef9e671e18d9093999/setup_posix.py\", line 31, in mysql_config\n",
      "        raise OSError(\"{} not found\".format(_mysql_config_path))\n",
      "    OSError: mysql_config not found\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/0e/68/f79de0e0fcdb041783124b825771e0ba6a3d0893b7b4c4735f130e42af47/mysqlclient-2.0.2.tar.gz#sha256=8df057b08fc27d8f7106bfa997d0a21e2acef017f905f06d6fb0aa6a20d4d2b2 (from https://pypi.org/simple/mysqlclient/) (requires-python:>=3.5). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/juliabecker/opt/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_493aa56f9c6b404c8829d3f6d1fcce39/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_493aa56f9c6b404c8829d3f6d1fcce39/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-pip-egg-info-hvp3e91f\n",
      "         cwd: /private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_493aa56f9c6b404c8829d3f6d1fcce39/\n",
      "    Complete output (12 lines):\n",
      "    /bin/sh: mysql_config: command not found\n",
      "    /bin/sh: mariadb_config: command not found\n",
      "    /bin/sh: mysql_config: command not found\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_493aa56f9c6b404c8829d3f6d1fcce39/setup.py\", line 15, in <module>\n",
      "        metadata, options = get_config()\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_493aa56f9c6b404c8829d3f6d1fcce39/setup_posix.py\", line 65, in get_config\n",
      "        libs = mysql_config(\"libs\")\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_493aa56f9c6b404c8829d3f6d1fcce39/setup_posix.py\", line 31, in mysql_config\n",
      "        raise OSError(\"{} not found\".format(_mysql_config_path))\n",
      "    OSError: mysql_config not found\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/a5/e1/e5f2b231c05dc51d9d87fa5066f90d1405345c54b14b0b11a1c859020f21/mysqlclient-2.0.1.tar.gz#sha256=fb2f75aea14722390d2d8ddf384ad99da708c707a96656210a7be8af20a2c5e5 (from https://pypi.org/simple/mysqlclient/) (requires-python:>=3.5). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/juliabecker/opt/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_f76f131b482d44e2a48861b3c104ed67/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_f76f131b482d44e2a48861b3c104ed67/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-pip-egg-info-430nf0gk\n",
      "         cwd: /private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_f76f131b482d44e2a48861b3c104ed67/\n",
      "    Complete output (12 lines):\n",
      "    /bin/sh: mysql_config: command not found\n",
      "    /bin/sh: mariadb_config: command not found\n",
      "    /bin/sh: mysql_config: command not found\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_f76f131b482d44e2a48861b3c104ed67/setup.py\", line 15, in <module>\n",
      "        metadata, options = get_config()\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_f76f131b482d44e2a48861b3c104ed67/setup_posix.py\", line 65, in get_config\n",
      "        libs = mysql_config(\"libs\")\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_f76f131b482d44e2a48861b3c104ed67/setup_posix.py\", line 31, in mysql_config\n",
      "        raise OSError(\"{} not found\".format(_mysql_config_path))\n",
      "    OSError: mysql_config not found\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/ca/cf/dd8124bf8b3d2ae465db9c8ce35c51650c31784b095f41faf6f8cad987a0/mysqlclient-2.0.0.tar.gz#sha256=201dfcc2a3c8a0859ea399947f1af8abe74b706beba0ebac149180d9d7b0f6e8 (from https://pypi.org/simple/mysqlclient/) (requires-python:>=3.5). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/juliabecker/opt/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_2e0823331c8b4a2d84e25a56d9de6a42/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_2e0823331c8b4a2d84e25a56d9de6a42/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-pip-egg-info-9byfrta5\n",
      "         cwd: /private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_2e0823331c8b4a2d84e25a56d9de6a42/\n",
      "    Complete output (12 lines):\n",
      "    /bin/sh: mysql_config: command not found\n",
      "    /bin/sh: mariadb_config: command not found\n",
      "    /bin/sh: mysql_config: command not found\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_2e0823331c8b4a2d84e25a56d9de6a42/setup.py\", line 16, in <module>\n",
      "        metadata, options = get_config()\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_2e0823331c8b4a2d84e25a56d9de6a42/setup_posix.py\", line 61, in get_config\n",
      "        libs = mysql_config(\"libs\")\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_2e0823331c8b4a2d84e25a56d9de6a42/setup_posix.py\", line 29, in mysql_config\n",
      "        raise EnvironmentError(\"%s not found\" % (_mysql_config_path,))\n",
      "    OSError: mysql_config not found\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/d0/97/7326248ac8d5049968bf4ec708a5d3d4806e412a42e74160d7f266a3e03a/mysqlclient-1.4.6.tar.gz#sha256=f3fdaa9a38752a3b214a6fe79d7cae3653731a53e577821f9187e67cbecb2e16 (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/juliabecker/opt/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_69ca577c503448c38294f0c04daa0e58/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_69ca577c503448c38294f0c04daa0e58/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-pip-egg-info-9038ob31\n",
      "         cwd: /private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_69ca577c503448c38294f0c04daa0e58/\n",
      "    Complete output (12 lines):\n",
      "    /bin/sh: mysql_config: command not found\n",
      "    /bin/sh: mariadb_config: command not found\n",
      "    /bin/sh: mysql_config: command not found\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_69ca577c503448c38294f0c04daa0e58/setup.py\", line 16, in <module>\n",
      "        metadata, options = get_config()\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_69ca577c503448c38294f0c04daa0e58/setup_posix.py\", line 61, in get_config\n",
      "        libs = mysql_config(\"libs\")\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_69ca577c503448c38294f0c04daa0e58/setup_posix.py\", line 29, in mysql_config\n",
      "        raise EnvironmentError(\"%s not found\" % (_mysql_config_path,))\n",
      "    OSError: mysql_config not found\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/f8/9b/5db9a03e2088a87c26e3e4d4c7f7e8f4c2dbae610f9521cdfac15755a795/mysqlclient-1.4.5.tar.gz#sha256=e80109b0ae8d952b900b31b623181532e5e89376d707dcbeb63f99e69cefe559 (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/juliabecker/opt/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_941aecc8c4004dcaa3d081014b7825ef/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_941aecc8c4004dcaa3d081014b7825ef/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-pip-egg-info-upoqkos0\n",
      "         cwd: /private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_941aecc8c4004dcaa3d081014b7825ef/\n",
      "    Complete output (12 lines):\n",
      "    /bin/sh: mysql_config: command not found\n",
      "    /bin/sh: mariadb_config: command not found\n",
      "    /bin/sh: mysql_config: command not found\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_941aecc8c4004dcaa3d081014b7825ef/setup.py\", line 16, in <module>\n",
      "        metadata, options = get_config()\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_941aecc8c4004dcaa3d081014b7825ef/setup_posix.py\", line 61, in get_config\n",
      "        libs = mysql_config(\"libs\")\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_941aecc8c4004dcaa3d081014b7825ef/setup_posix.py\", line 29, in mysql_config\n",
      "        raise EnvironmentError(\"%s not found\" % (_mysql_config_path,))\n",
      "    OSError: mysql_config not found\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/4d/38/c5f8bac9c50f3042c8f05615f84206f77f03db79781db841898fde1bb284/mysqlclient-1.4.4.tar.gz#sha256=9c737cc55a5dc8dd3583a942d5a9b21be58d16f00f5fefca4e575e7d9682e98c (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/juliabecker/opt/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_42bdcb7ef82b4e308f68b7b8adc001eb/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_42bdcb7ef82b4e308f68b7b8adc001eb/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-pip-egg-info-twew7_gp\n",
      "         cwd: /private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_42bdcb7ef82b4e308f68b7b8adc001eb/\n",
      "    Complete output (12 lines):\n",
      "    /bin/sh: mysql_config: command not found\n",
      "    /bin/sh: mariadb_config: command not found\n",
      "    /bin/sh: mysql_config: command not found\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_42bdcb7ef82b4e308f68b7b8adc001eb/setup.py\", line 16, in <module>\n",
      "        metadata, options = get_config()\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_42bdcb7ef82b4e308f68b7b8adc001eb/setup_posix.py\", line 61, in get_config\n",
      "        libs = mysql_config(\"libs\")\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_42bdcb7ef82b4e308f68b7b8adc001eb/setup_posix.py\", line 29, in mysql_config\n",
      "        raise EnvironmentError(\"%s not found\" % (_mysql_config_path,))\n",
      "    OSError: mysql_config not found\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/13/37/6c941aabeb78464a538b7d43266bfae645993779e3ca3e12fe82b4590f52/mysqlclient-1.4.3.tar.gz#sha256=0d3eeb97534c9f42e9b65bd35c1a35fadc2f6d7ea5d9fdbda5339a569156344b (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/juliabecker/opt/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_946f26a080a541f48fb10aa337770030/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_946f26a080a541f48fb10aa337770030/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-pip-egg-info-i9kh1cz4\n",
      "         cwd: /private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_946f26a080a541f48fb10aa337770030/\n",
      "    Complete output (10 lines):\n",
      "    /bin/sh: mysql_config: command not found\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_946f26a080a541f48fb10aa337770030/setup.py\", line 16, in <module>\n",
      "        metadata, options = get_config()\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_946f26a080a541f48fb10aa337770030/setup_posix.py\", line 51, in get_config\n",
      "        libs = mysql_config(\"libs\")\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_946f26a080a541f48fb10aa337770030/setup_posix.py\", line 29, in mysql_config\n",
      "        raise EnvironmentError(\"%s not found\" % (_mysql_config_path,))\n",
      "    OSError: mysql_config not found\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/f4/f1/3bb6f64ca7a429729413e6556b7ba5976df06019a5245a43d36032f1061e/mysqlclient-1.4.2.post1.tar.gz#sha256=f257d250f2675d0ef99bd318906f3cfc05cef4a2f385ea695ff32a3f04b9f9a7 (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/juliabecker/opt/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_ee8580d87e5f49139204ecbf950924f1/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_ee8580d87e5f49139204ecbf950924f1/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-pip-egg-info-a87kk7yr\n",
      "         cwd: /private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_ee8580d87e5f49139204ecbf950924f1/\n",
      "    Complete output (10 lines):\n",
      "    /bin/sh: mysql_config: command not found\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_ee8580d87e5f49139204ecbf950924f1/setup.py\", line 16, in <module>\n",
      "        metadata, options = get_config()\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_ee8580d87e5f49139204ecbf950924f1/setup_posix.py\", line 51, in get_config\n",
      "        libs = mysql_config(\"libs\")\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_ee8580d87e5f49139204ecbf950924f1/setup_posix.py\", line 29, in mysql_config\n",
      "        raise EnvironmentError(\"%s not found\" % (_mysql_config_path,))\n",
      "    OSError: mysql_config not found\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/73/79/67ddf24ac31b05d741f0ac87fa612c7a11bab1b39b8270ed7344d149f8af/mysqlclient-1.4.2.tar.gz#sha256=b95edaa41d6cc47deecabcdcbb5ab437ad9ae6d8955f5cf10d1847b37e66ef5e (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/juliabecker/opt/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_dfef9fae35c94fb7aed754222eea0d83/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_dfef9fae35c94fb7aed754222eea0d83/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-pip-egg-info-cg9e6eop\n",
      "         cwd: /private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_dfef9fae35c94fb7aed754222eea0d83/\n",
      "    Complete output (10 lines):\n",
      "    /bin/sh: mysql_config: command not found\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_dfef9fae35c94fb7aed754222eea0d83/setup.py\", line 16, in <module>\n",
      "        metadata, options = get_config()\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_dfef9fae35c94fb7aed754222eea0d83/setup_posix.py\", line 51, in get_config\n",
      "        libs = mysql_config(\"libs\")\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_dfef9fae35c94fb7aed754222eea0d83/setup_posix.py\", line 29, in mysql_config\n",
      "        raise EnvironmentError(\"%s not found\" % (_mysql_config_path,))\n",
      "    OSError: mysql_config not found\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/de/d7/919042fb7ed78a89e21c4e43d5daed90d5df18ec183bae3de493a7d9e3ed/mysqlclient-1.4.1.tar.gz#sha256=a62220410e26ce2d2ff94dd0138c3ecfb91db634464a9afb4c8e6b50f0a67e00 (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/juliabecker/opt/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_3c0ea16f286149be854c7a472b319ca1/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_3c0ea16f286149be854c7a472b319ca1/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-pip-egg-info-jtyjci4d\n",
      "         cwd: /private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_3c0ea16f286149be854c7a472b319ca1/\n",
      "    Complete output (10 lines):\n",
      "    /bin/sh: mysql_config: command not found\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_3c0ea16f286149be854c7a472b319ca1/setup.py\", line 16, in <module>\n",
      "        metadata, options = get_config()\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_3c0ea16f286149be854c7a472b319ca1/setup_posix.py\", line 51, in get_config\n",
      "        libs = mysql_config(\"libs\")\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_3c0ea16f286149be854c7a472b319ca1/setup_posix.py\", line 29, in mysql_config\n",
      "        raise EnvironmentError(\"%s not found\" % (_mysql_config_path,))\n",
      "    OSError: mysql_config not found\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/05/73/fac741eef89b0257fb1807de80e96474f40d52739cdbc32c90c4a793e79d/mysqlclient-1.4.0.tar.gz#sha256=efeaacd04feea7d44fef2a5adf4df335b438458f8b89144307dc5a90025761a5 (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/juliabecker/opt/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_27d416b469904f84afd405f09c5d913b/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_27d416b469904f84afd405f09c5d913b/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-pip-egg-info-vq02icbv\n",
      "         cwd: /private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_27d416b469904f84afd405f09c5d913b/\n",
      "    Complete output (10 lines):\n",
      "    /bin/sh: mysql_config: command not found\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_27d416b469904f84afd405f09c5d913b/setup.py\", line 16, in <module>\n",
      "        metadata, options = get_config()\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_27d416b469904f84afd405f09c5d913b/setup_posix.py\", line 53, in get_config\n",
      "        libs = mysql_config(\"libs_r\")\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_27d416b469904f84afd405f09c5d913b/setup_posix.py\", line 28, in mysql_config\n",
      "        raise EnvironmentError(\"%s not found\" % (mysql_config.path,))\n",
      "    OSError: mysql_config not found\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/f7/a2/1230ebbb4b91f42ad6b646e59eb8855559817ad5505d81c1ca2b5a216040/mysqlclient-1.3.14.tar.gz#sha256=3981ae9ce545901a36a8b7aed76ed02960a429f75dc53b7ad77fb2f9ab7cd56b (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/juliabecker/opt/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_832f81563b894ba3a51536d7b295853c/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_832f81563b894ba3a51536d7b295853c/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-pip-egg-info-rib9ow3v\n",
      "         cwd: /private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_832f81563b894ba3a51536d7b295853c/\n",
      "    Complete output (10 lines):\n",
      "    /bin/sh: mysql_config: command not found\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_832f81563b894ba3a51536d7b295853c/setup.py\", line 18, in <module>\n",
      "        metadata, options = get_config()\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_832f81563b894ba3a51536d7b295853c/setup_posix.py\", line 53, in get_config\n",
      "        libs = mysql_config(\"libs_r\")\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_832f81563b894ba3a51536d7b295853c/setup_posix.py\", line 28, in mysql_config\n",
      "        raise EnvironmentError(\"%s not found\" % (mysql_config.path,))\n",
      "    OSError: mysql_config not found\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/ec/fd/83329b9d3e14f7344d1cb31f128e6dbba70c5975c9e57896815dbb1988ad/mysqlclient-1.3.13.tar.gz#sha256=ff8ee1be84215e6c30a746b728c41eb0701a46ca76e343af445b35ce6250644f (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/juliabecker/opt/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_94d72c008dd04f529d468a0699d743aa/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_94d72c008dd04f529d468a0699d743aa/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-pip-egg-info-qbk35x9r\n",
      "         cwd: /private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_94d72c008dd04f529d468a0699d743aa/\n",
      "    Complete output (10 lines):\n",
      "    /bin/sh: mysql_config: command not found\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_94d72c008dd04f529d468a0699d743aa/setup.py\", line 17, in <module>\n",
      "        metadata, options = get_config()\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_94d72c008dd04f529d468a0699d743aa/setup_posix.py\", line 44, in get_config\n",
      "        libs = mysql_config(\"libs_r\")\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_94d72c008dd04f529d468a0699d743aa/setup_posix.py\", line 26, in mysql_config\n",
      "        raise EnvironmentError(\"%s not found\" % (mysql_config.path,))\n",
      "    OSError: mysql_config not found\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/6f/86/bad31f1c1bb0cc99e88ca2adb7cb5c71f7a6540c1bb001480513de76a931/mysqlclient-1.3.12.tar.gz#sha256=2d9ec33de39f4d9c64ad7322ede0521d85829ce36a76f9dd3d6ab76a9c8648e5 (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/juliabecker/opt/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_4a0a22da87304979bd664f591d015ae9/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_4a0a22da87304979bd664f591d015ae9/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-pip-egg-info-8wqypr54\n",
      "         cwd: /private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_4a0a22da87304979bd664f591d015ae9/\n",
      "    Complete output (10 lines):\n",
      "    /bin/sh: mysql_config: command not found\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_4a0a22da87304979bd664f591d015ae9/setup.py\", line 17, in <module>\n",
      "        metadata, options = get_config()\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_4a0a22da87304979bd664f591d015ae9/setup_posix.py\", line 44, in get_config\n",
      "        libs = mysql_config(\"libs_r\")\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_4a0a22da87304979bd664f591d015ae9/setup_posix.py\", line 26, in mysql_config\n",
      "        raise EnvironmentError(\"%s not found\" % (mysql_config.path,))\n",
      "    OSError: mysql_config not found\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/6a/4d/856d1848e9b7fa8577a31c0188592f472e5cbc94f588c2a40ff930533d73/mysqlclient-1.3.11.tar.gz#sha256=9a79b38843d61f651266ff16b9fdcc8830d21f0fb852e4406a19e9a715bdf3e2 (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/juliabecker/opt/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_dff00a1b33fe4196ba224187a8ba4d80/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_dff00a1b33fe4196ba224187a8ba4d80/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-pip-egg-info-s447i70u\n",
      "         cwd: /private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_dff00a1b33fe4196ba224187a8ba4d80/\n",
      "    Complete output (10 lines):\n",
      "    /bin/sh: mysql_config: command not found\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_dff00a1b33fe4196ba224187a8ba4d80/setup.py\", line 17, in <module>\n",
      "        metadata, options = get_config()\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_dff00a1b33fe4196ba224187a8ba4d80/setup_posix.py\", line 44, in get_config\n",
      "        libs = mysql_config(\"libs_r\")\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_dff00a1b33fe4196ba224187a8ba4d80/setup_posix.py\", line 26, in mysql_config\n",
      "        raise EnvironmentError(\"%s not found\" % (mysql_config.path,))\n",
      "    OSError: mysql_config not found\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/40/9b/0bc869f290b8f49a99b8d97927f57126a5d1befcf8bac92c60dc855f2523/mysqlclient-1.3.10.tar.gz#sha256=452aaf9d2ba1a4fb85c134c88f9b1857852deed63b3b13255d7a65d2c1297262 (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/juliabecker/opt/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_c1e9931e3c6945cfaaf27583d9bd9688/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_c1e9931e3c6945cfaaf27583d9bd9688/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-pip-egg-info-do7vojz5\n",
      "         cwd: /private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_c1e9931e3c6945cfaaf27583d9bd9688/\n",
      "    Complete output (10 lines):\n",
      "    /bin/sh: mysql_config: command not found\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_c1e9931e3c6945cfaaf27583d9bd9688/setup.py\", line 17, in <module>\n",
      "        metadata, options = get_config()\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_c1e9931e3c6945cfaaf27583d9bd9688/setup_posix.py\", line 44, in get_config\n",
      "        libs = mysql_config(\"libs_r\")\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_c1e9931e3c6945cfaaf27583d9bd9688/setup_posix.py\", line 26, in mysql_config\n",
      "        raise EnvironmentError(\"%s not found\" % (mysql_config.path,))\n",
      "    OSError: mysql_config not found\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/db/f5/c8e1657985c31dda16e434edf5257c31572fa5faacd7e48b1618390e4b18/mysqlclient-1.3.9.tar.gz#sha256=990ccf1e1f15b9a291b811c993dc1c216566714bc14e6581b38665bd61c28c99 (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/juliabecker/opt/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_2ad93f8dd7244ce5b30d9942d74202cc/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_2ad93f8dd7244ce5b30d9942d74202cc/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-pip-egg-info-07lamm0b\n",
      "         cwd: /private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_2ad93f8dd7244ce5b30d9942d74202cc/\n",
      "    Complete output (10 lines):\n",
      "    /bin/sh: mysql_config: command not found\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_2ad93f8dd7244ce5b30d9942d74202cc/setup.py\", line 17, in <module>\n",
      "        metadata, options = get_config()\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_2ad93f8dd7244ce5b30d9942d74202cc/setup_posix.py\", line 44, in get_config\n",
      "        libs = mysql_config(\"libs_r\")\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_2ad93f8dd7244ce5b30d9942d74202cc/setup_posix.py\", line 26, in mysql_config\n",
      "        raise EnvironmentError(\"%s not found\" % (mysql_config.path,))\n",
      "    OSError: mysql_config not found\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/31/ce/7ea049b3d5929b3cce3104967ccca218a9f054517f0d15dfdaf4e76da2a0/mysqlclient-1.3.8.tar.gz#sha256=c64bc386c0b771ed6ff76de0f52e0f957f98d9e13c83b0ddb821afdbe3f5d970 (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/juliabecker/opt/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_e705f53e5dc142ce9e8bb438fbda9114/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_e705f53e5dc142ce9e8bb438fbda9114/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-pip-egg-info-zc65o84t\n",
      "         cwd: /private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_e705f53e5dc142ce9e8bb438fbda9114/\n",
      "    Complete output (10 lines):\n",
      "    /bin/sh: mysql_config: command not found\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_e705f53e5dc142ce9e8bb438fbda9114/setup.py\", line 17, in <module>\n",
      "        metadata, options = get_config()\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_e705f53e5dc142ce9e8bb438fbda9114/setup_posix.py\", line 44, in get_config\n",
      "        libs = mysql_config(\"libs_r\")\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_e705f53e5dc142ce9e8bb438fbda9114/setup_posix.py\", line 26, in mysql_config\n",
      "        raise EnvironmentError(\"%s not found\" % (mysql_config.path,))\n",
      "    OSError: mysql_config not found\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/74/ff/4e964e20b559e55d7afa60fbccc6a560f2adf289813bd3d7eb4eb8a87093/mysqlclient-1.3.7.tar.gz#sha256=c74a83b4cb2933d0e43370117eeebdfa03077ae72686d2df43d31879267f1f1b (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/juliabecker/opt/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_5397f276461f463c8a12a121d89048bb/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_5397f276461f463c8a12a121d89048bb/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-pip-egg-info-297vey8y\n",
      "         cwd: /private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_5397f276461f463c8a12a121d89048bb/\n",
      "    Complete output (10 lines):\n",
      "    /bin/sh: mysql_config: command not found\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_5397f276461f463c8a12a121d89048bb/setup.py\", line 17, in <module>\n",
      "        metadata, options = get_config()\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_5397f276461f463c8a12a121d89048bb/setup_posix.py\", line 47, in get_config\n",
      "        libs = mysql_config(\"libs_r\")\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_5397f276461f463c8a12a121d89048bb/setup_posix.py\", line 29, in mysql_config\n",
      "        raise EnvironmentError(\"%s not found\" % (mysql_config.path,))\n",
      "    OSError: mysql_config not found\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/09/29/6648563af4b45798ba667f17ea55166d7b0ed8717937c06977a1fdbe7df6/mysqlclient-1.3.6.tar.gz#sha256=1f63a8ab111530a0ff9acaeb118074f11e7564b7c124f2e7fc56fcac641aecf2 (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/juliabecker/opt/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_198966fc0aaf470fa10b86ee6c80816c/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_198966fc0aaf470fa10b86ee6c80816c/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-pip-egg-info-ovt96rob\n",
      "         cwd: /private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_198966fc0aaf470fa10b86ee6c80816c/\n",
      "    Complete output (10 lines):\n",
      "    /bin/sh: mysql_config: command not found\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_198966fc0aaf470fa10b86ee6c80816c/setup.py\", line 17, in <module>\n",
      "        metadata, options = get_config()\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_198966fc0aaf470fa10b86ee6c80816c/setup_posix.py\", line 47, in get_config\n",
      "        libs = mysql_config(\"libs_r\")\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_198966fc0aaf470fa10b86ee6c80816c/setup_posix.py\", line 29, in mysql_config\n",
      "        raise EnvironmentError(\"%s not found\" % (mysql_config.path,))\n",
      "    OSError: mysql_config not found\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/82/ea/336daf6c7baa564d0c434ab748218d1a7dc61dfc7066e98b72afd24fd2b9/mysqlclient-1.3.5.tar.gz#sha256=80ea68f6f3c2cfbf35c91adde2b40de1f2c31132118d2dcee048c72423f678bf (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/juliabecker/opt/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_e7da5665c8bc4f3594a1ae0c84681499/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_e7da5665c8bc4f3594a1ae0c84681499/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-pip-egg-info-acwcq9wj\n",
      "         cwd: /private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_e7da5665c8bc4f3594a1ae0c84681499/\n",
      "    Complete output (10 lines):\n",
      "    /bin/sh: mysql_config: command not found\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_e7da5665c8bc4f3594a1ae0c84681499/setup.py\", line 17, in <module>\n",
      "        metadata, options = get_config()\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_e7da5665c8bc4f3594a1ae0c84681499/setup_posix.py\", line 47, in get_config\n",
      "        libs = mysql_config(\"libs_r\")\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_e7da5665c8bc4f3594a1ae0c84681499/setup_posix.py\", line 29, in mysql_config\n",
      "        raise EnvironmentError(\"%s not found\" % (mysql_config.path,))\n",
      "    OSError: mysql_config not found\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/17/d9/03b08e6a033401335b720806b87596aee8d7f7aa87539713238905c4a8d1/mysqlclient-1.3.4.tar.gz#sha256=a0263383f8ac33ad12d68dc61fa8ccbee41244ce916287c6cee71bf8aea82c5c (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/juliabecker/opt/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_10a57ec707db49db9215314a92cde51b/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_10a57ec707db49db9215314a92cde51b/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-pip-egg-info-heak497h\n",
      "         cwd: /private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_10a57ec707db49db9215314a92cde51b/\n",
      "    Complete output (10 lines):\n",
      "    /bin/sh: mysql_config: command not found\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_10a57ec707db49db9215314a92cde51b/setup.py\", line 17, in <module>\n",
      "        metadata, options = get_config()\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_10a57ec707db49db9215314a92cde51b/setup_posix.py\", line 47, in get_config\n",
      "        libs = mysql_config(\"libs_r\")\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_10a57ec707db49db9215314a92cde51b/setup_posix.py\", line 29, in mysql_config\n",
      "        raise EnvironmentError(\"%s not found\" % (mysql_config.path,))\n",
      "    OSError: mysql_config not found\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/26/53/c575db342bfca0213c9243ed2642bfadcd420b18d2f477dc812543e3d83a/mysqlclient-1.3.3.tar.gz#sha256=0f0887882d71bf2a079d9724d9323053cfbee8ab2dcfc989daf97d7ce5be9af9 (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/juliabecker/opt/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_f5cae79d3a014433b68a8671b1548764/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_f5cae79d3a014433b68a8671b1548764/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-pip-egg-info-y324cgep\n",
      "         cwd: /private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_f5cae79d3a014433b68a8671b1548764/\n",
      "    Complete output (10 lines):\n",
      "    /bin/sh: mysql_config: command not found\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_f5cae79d3a014433b68a8671b1548764/setup.py\", line 17, in <module>\n",
      "        metadata, options = get_config()\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_f5cae79d3a014433b68a8671b1548764/setup_posix.py\", line 47, in get_config\n",
      "        libs = mysql_config(\"libs_r\")\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_f5cae79d3a014433b68a8671b1548764/setup_posix.py\", line 29, in mysql_config\n",
      "        raise EnvironmentError(\"%s not found\" % (mysql_config.path,))\n",
      "    OSError: mysql_config not found\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/2d/df/5440ee86bbb248325cdd6e1fc9cbbba365018a0d2d57f673610e020e6b1d/mysqlclient-1.3.2.tar.gz#sha256=e44025830501b9f70f8c2fe8eeff66f0df2df198802f7295801dac199b8236ef (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/juliabecker/opt/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_8fba590329c44c8aa23b51150cc81e17/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_8fba590329c44c8aa23b51150cc81e17/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-pip-egg-info-516fruub\n",
      "         cwd: /private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_8fba590329c44c8aa23b51150cc81e17/\n",
      "    Complete output (10 lines):\n",
      "    /bin/sh: mysql_config: command not found\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_8fba590329c44c8aa23b51150cc81e17/setup.py\", line 17, in <module>\n",
      "        metadata, options = get_config()\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_8fba590329c44c8aa23b51150cc81e17/setup_posix.py\", line 47, in get_config\n",
      "        libs = mysql_config(\"libs_r\")\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_8fba590329c44c8aa23b51150cc81e17/setup_posix.py\", line 29, in mysql_config\n",
      "        raise EnvironmentError(\"%s not found\" % (mysql_config.path,))\n",
      "    OSError: mysql_config not found\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/6b/ba/4729d99e85a0a35bb46d55500570de05b4af10431cef174b6da9f58a0e50/mysqlclient-1.3.1.tar.gz#sha256=3549e8a61f10c8cd8eac6581d3f44d0594f535fb7b29e6090db3a0bc547b25ad (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/juliabecker/opt/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_c930a833e17c4fc2934ac0c3efe85a0d/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_c930a833e17c4fc2934ac0c3efe85a0d/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-pip-egg-info-kohcjsg1\n",
      "         cwd: /private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_c930a833e17c4fc2934ac0c3efe85a0d/\n",
      "    Complete output (10 lines):\n",
      "    /bin/sh: mysql_config: command not found\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_c930a833e17c4fc2934ac0c3efe85a0d/setup.py\", line 17, in <module>\n",
      "        metadata, options = get_config()\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_c930a833e17c4fc2934ac0c3efe85a0d/setup_posix.py\", line 47, in get_config\n",
      "        libs = mysql_config(\"libs_r\")\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysqlclient_c930a833e17c4fc2934ac0c3efe85a0d/setup_posix.py\", line 29, in mysql_config\n",
      "        raise EnvironmentError(\"%s not found\" % (mysql_config.path,))\n",
      "    OSError: mysql_config not found\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/6a/91/bdfe808fb5dc99a5f65833b370818161b77ef6d1e19b488e4c146ab615aa/mysqlclient-1.3.0.tar.gz#sha256=06eb5664e3738b283ea2262ee60ed83192e898f019cc7ff251f4d05a564ab3b7 (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/juliabecker/opt/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysql-python_2d7a47fbdbd14aeab55c37b4f2873271/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysql-python_2d7a47fbdbd14aeab55c37b4f2873271/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-pip-egg-info-qmsh5emb\n",
      "         cwd: /private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysql-python_2d7a47fbdbd14aeab55c37b4f2873271/\n",
      "    Complete output (7 lines):\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysql-python_2d7a47fbdbd14aeab55c37b4f2873271/setup.py\", line 13, in <module>\n",
      "        from setup_posix import get_config\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysql-python_2d7a47fbdbd14aeab55c37b4f2873271/setup_posix.py\", line 2, in <module>\n",
      "        from ConfigParser import SafeConfigParser\n",
      "    ModuleNotFoundError: No module named 'ConfigParser'\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/a5/e9/51b544da85a36a68debe7a7091f068d802fc515a3a202652828c73453cad/MySQL-python-1.2.5.zip#sha256=811040b647e5d5686f84db415efd697e6250008b112b6909ba77ac059e140c74 (from https://pypi.org/simple/mysql-python/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/juliabecker/opt/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysql-python_aa60499dea1e4fa2a700e93b0b4a29ee/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysql-python_aa60499dea1e4fa2a700e93b0b4a29ee/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-pip-egg-info-o_snc4d0\n",
      "         cwd: /private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysql-python_aa60499dea1e4fa2a700e93b0b4a29ee/\n",
      "    Complete output (31 lines):\n",
      "    Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.28.tar.gz\n",
      "    Traceback (most recent call last):\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysql-python_aa60499dea1e4fa2a700e93b0b4a29ee/distribute_setup.py\", line 143, in use_setuptools\n",
      "        raise ImportError\n",
      "    ImportError\n",
      "    \n",
      "    During handling of the above exception, another exception occurred:\n",
      "    \n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysql-python_aa60499dea1e4fa2a700e93b0b4a29ee/setup.py\", line 7, in <module>\n",
      "        use_setuptools()\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysql-python_aa60499dea1e4fa2a700e93b0b4a29ee/distribute_setup.py\", line 145, in use_setuptools\n",
      "        return _do_download(version, download_base, to_dir, download_delay)\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysql-python_aa60499dea1e4fa2a700e93b0b4a29ee/distribute_setup.py\", line 123, in _do_download\n",
      "        tarball = download_setuptools(version, download_base,\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysql-python_aa60499dea1e4fa2a700e93b0b4a29ee/distribute_setup.py\", line 194, in download_setuptools\n",
      "        src = urlopen(url)\n",
      "      File \"/Users/juliabecker/opt/anaconda3/lib/python3.8/urllib/request.py\", line 222, in urlopen\n",
      "        return opener.open(url, data, timeout)\n",
      "      File \"/Users/juliabecker/opt/anaconda3/lib/python3.8/urllib/request.py\", line 531, in open\n",
      "        response = meth(req, response)\n",
      "      File \"/Users/juliabecker/opt/anaconda3/lib/python3.8/urllib/request.py\", line 640, in http_response\n",
      "        response = self.parent.error(\n",
      "      File \"/Users/juliabecker/opt/anaconda3/lib/python3.8/urllib/request.py\", line 569, in error\n",
      "        return self._call_chain(*args)\n",
      "      File \"/Users/juliabecker/opt/anaconda3/lib/python3.8/urllib/request.py\", line 502, in _call_chain\n",
      "        result = func(*args)\n",
      "      File \"/Users/juliabecker/opt/anaconda3/lib/python3.8/urllib/request.py\", line 649, in http_error_default\n",
      "        raise HTTPError(req.full_url, code, msg, hdrs, fp)\n",
      "    urllib.error.HTTPError: HTTP Error 403: SSL is required\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/90/5a/ce7bef80825c2188cf507baf57b37516e18dffdb198a6766a597f703059a/MySQL-python-1.2.4.zip#sha256=e405f9d6be33923d428acaa4db4f4470427f1d15ea0d2d82a933449ace26bbd9 (from https://pypi.org/simple/mysql-python/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[31m    ERROR: Command errored out with exit status 1:\n",
      "     command: /Users/juliabecker/opt/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '\"'\"'/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysql-python_4dff6d80add14fed97a23c334cb4e1db/setup.py'\"'\"'; __file__='\"'\"'/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysql-python_4dff6d80add14fed97a23c334cb4e1db/setup.py'\"'\"';f=getattr(tokenize, '\"'\"'open'\"'\"', open)(__file__);code=f.read().replace('\"'\"'\\r\\n'\"'\"', '\"'\"'\\n'\"'\"');f.close();exec(compile(code, __file__, '\"'\"'exec'\"'\"'))' egg_info --egg-base /private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-pip-egg-info-jw0quow8\n",
      "         cwd: /private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysql-python_4dff6d80add14fed97a23c334cb4e1db/\n",
      "    Complete output (8 lines):\n",
      "    Traceback (most recent call last):\n",
      "      File \"<string>\", line 1, in <module>\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysql-python_4dff6d80add14fed97a23c334cb4e1db/setup.py\", line 11, in <module>\n",
      "        from setup_posix import get_config\n",
      "      File \"/private/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/pip-install-6u3qedcy/mysql-python_4dff6d80add14fed97a23c334cb4e1db/setup_posix.py\", line 101\n",
      "        print \"\"\"You shouldn't be running this directly; it is used by setup.py.\"\"\"\n",
      "              ^\n",
      "    SyntaxError: Missing parentheses in call to 'print'. Did you mean print(\"\"\"You shouldn't be running this directly)?\n",
      "    ----------------------------------------\u001b[0m\n",
      "\u001b[33mWARNING: Discarding https://files.pythonhosted.org/packages/9a/81/924d6799494cf7fb24370335c2f782088d6ac4f79e4137d4df94cea3582c/MySQL-python-1.2.3.tar.gz#sha256=7de66fbbf923634e7c965aeaefa74642ba75ae20ee1cefcefc3009595b7a7e6e (from https://pypi.org/simple/mysql-python/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.\u001b[0m\n",
      "\u001b[31mERROR: Cannot install mysql==0.0.1, mysql==0.0.2 and mysql==0.0.3 because these package versions have conflicting dependencies.\u001b[0m\n",
      "\u001b[31mERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies\u001b[0m\n",
      "Collecting mysql-connector-python-rf\n",
      "  Downloading mysql-connector-python-rf-2.2.2.tar.gz (11.9 MB)\n",
      "\u001b[K     |████████████████████████████████| 11.9 MB 5.0 MB/s eta 0:00:01\n",
      "\u001b[?25hBuilding wheels for collected packages: mysql-connector-python-rf\n",
      "  Building wheel for mysql-connector-python-rf (setup.py) ... \u001b[?25ldone\n",
      "\u001b[?25h  Created wheel for mysql-connector-python-rf: filename=mysql_connector_python_rf-2.2.2-cp38-cp38-macosx_10_9_x86_64.whl size=249463 sha256=ec2fc9d9cfcc4e2025aeb4205628d85eeac3f549e09db74199c3df3fa132628f\n",
      "  Stored in directory: /Users/juliabecker/Library/Caches/pip/wheels/f5/66/87/6d9cef740fd440ef390930fdbe6c761dc1efef78ec94a288fd\n",
      "Successfully built mysql-connector-python-rf\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Installing collected packages: mysql-connector-python-rf\n",
      "Successfully installed mysql-connector-python-rf-2.2.2\n"
     ]
    }
   ],
   "source": [
    "import os\n",
    "# Find the latest version of spark 3.0 from http://www.apache.org/dist/spark/ and enter as the spark version\n",
    "# For example:\n",
    "# spark_version = 'spark-3.0.3'\n",
    "spark_version = 'spark-3.2.0'\n",
    "os.environ['SPARK_VERSION']=spark_version\n",
    "\n",
    "# Install Spark and Java\n",
    "!apt-get update\n",
    "!apt-get install openjdk-11-jdk-headless -qq > /dev/null\n",
    "!wget -q https://downloads.apache.org/spark/spark-3.2.0/spark-3.2.0-bin-hadoop2.7.tgz\n",
    "!wget -q http://www.java2s.com/Code/JarDownload/mysql/mysql-connector-java-5.1.17-bin.jar.zip\n",
    "!tar xf spark-3.2.0-bin-hadoop2.7.tgz\n",
    "!pip install -q findspark\n",
    "!pip install -q pymysql\n",
    "!pip install -q sqlalchemy\n",
    "!pip install -q mysql\n",
    "!pip install mysql-connector-python-rf\n",
    "\n",
    "# Set Environment Variables\n",
    "import os\n",
    "os.environ[\"JAVA_HOME\"] = \"/usr/lib/jvm/java-11-openjdk-amd64\"\n",
    "os.environ[\"SPARK_HOME\"] = f\"/content/{spark_version}-bin-hadoop2.7\"\n",
    "\n",
    "# Start a SparkSession\n",
    "import findspark\n",
    "findspark.init()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "id": "0f839ced",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "zsh:1: command not found: wget\r\n"
     ]
    }
   ],
   "source": [
    "# Download the Postgres driver that will allow Spark to interact with Postgres.\n",
    "!wget https://jdbc.postgresql.org/download/postgresql-42.2.16.jar"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "4a1b86be",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/juliabecker/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages/pyspark/bin/spark-class: line 71: /usr/lib/jvm/java-11-openjdk-amd64/bin/java: No such file or directory\n",
      "/Users/juliabecker/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages/pyspark/bin/spark-class: line 96: CMD: bad array subscript\n",
      "head: illegal line count -- -1\n"
     ]
    },
    {
     "ename": "RuntimeError",
     "evalue": "Java gateway process exited before sending its port number",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mRuntimeError\u001b[0m                              Traceback (most recent call last)",
      "\u001b[0;32m/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/ipykernel_94707/2333364693.py\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[0;32mfrom\u001b[0m \u001b[0mpyspark\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0msql\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mSparkSession\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 2\u001b[0;31m \u001b[0mspark\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mSparkSession\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mbuilder\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mappName\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"BigData-Challenge\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mconfig\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"spark.driver.extraClassPath\"\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\"/content/postgresql-42.2.16.jar\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mgetOrCreate\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[0;32m~/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages/pyspark/sql/session.py\u001b[0m in \u001b[0;36mgetOrCreate\u001b[0;34m(self)\u001b[0m\n\u001b[1;32m    226\u001b[0m                             \u001b[0msparkConf\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mset\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mkey\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mvalue\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    227\u001b[0m                         \u001b[0;31m# This SparkContext may be an existing one.\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 228\u001b[0;31m                         \u001b[0msc\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mSparkContext\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mgetOrCreate\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0msparkConf\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    229\u001b[0m                     \u001b[0;31m# Do not update `SparkConf` for existing `SparkContext`, as it's shared\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    230\u001b[0m                     \u001b[0;31m# by all sessions.\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages/pyspark/context.py\u001b[0m in \u001b[0;36mgetOrCreate\u001b[0;34m(cls, conf)\u001b[0m\n\u001b[1;32m    390\u001b[0m         \u001b[0;32mwith\u001b[0m \u001b[0mSparkContext\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_lock\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    391\u001b[0m             \u001b[0;32mif\u001b[0m \u001b[0mSparkContext\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_active_spark_context\u001b[0m \u001b[0;32mis\u001b[0m \u001b[0;32mNone\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 392\u001b[0;31m                 \u001b[0mSparkContext\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mconf\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mconf\u001b[0m \u001b[0;32mor\u001b[0m \u001b[0mSparkConf\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    393\u001b[0m             \u001b[0;32mreturn\u001b[0m \u001b[0mSparkContext\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_active_spark_context\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    394\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages/pyspark/context.py\u001b[0m in \u001b[0;36m__init__\u001b[0;34m(self, master, appName, sparkHome, pyFiles, environment, batchSize, serializer, conf, gateway, jsc, profiler_cls)\u001b[0m\n\u001b[1;32m    142\u001b[0m                 \" is not allowed as it is a security risk.\")\n\u001b[1;32m    143\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 144\u001b[0;31m         \u001b[0mSparkContext\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_ensure_initialized\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mgateway\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mgateway\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mconf\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mconf\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    145\u001b[0m         \u001b[0;32mtry\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    146\u001b[0m             self._do_init(master, appName, sparkHome, pyFiles, environment, batchSize, serializer,\n",
      "\u001b[0;32m~/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages/pyspark/context.py\u001b[0m in \u001b[0;36m_ensure_initialized\u001b[0;34m(cls, instance, gateway, conf)\u001b[0m\n\u001b[1;32m    337\u001b[0m         \u001b[0;32mwith\u001b[0m \u001b[0mSparkContext\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_lock\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    338\u001b[0m             \u001b[0;32mif\u001b[0m \u001b[0;32mnot\u001b[0m \u001b[0mSparkContext\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_gateway\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 339\u001b[0;31m                 \u001b[0mSparkContext\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_gateway\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mgateway\u001b[0m \u001b[0;32mor\u001b[0m \u001b[0mlaunch_gateway\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mconf\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    340\u001b[0m                 \u001b[0mSparkContext\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_jvm\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mSparkContext\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_gateway\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mjvm\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    341\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/opt/anaconda3/envs/PythonData/lib/python3.7/site-packages/pyspark/java_gateway.py\u001b[0m in \u001b[0;36mlaunch_gateway\u001b[0;34m(conf, popen_kwargs)\u001b[0m\n\u001b[1;32m    106\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    107\u001b[0m             \u001b[0;32mif\u001b[0m \u001b[0;32mnot\u001b[0m \u001b[0mos\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mpath\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0misfile\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mconn_info_file\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 108\u001b[0;31m                 \u001b[0;32mraise\u001b[0m \u001b[0mRuntimeError\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"Java gateway process exited before sending its port number\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    109\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    110\u001b[0m             \u001b[0;32mwith\u001b[0m \u001b[0mopen\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mconn_info_file\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m\"rb\"\u001b[0m\u001b[0;34m)\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0minfo\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mRuntimeError\u001b[0m: Java gateway process exited before sending its port number"
     ]
    }
   ],
   "source": [
    "from pyspark.sql import SparkSession\n",
    "spark = SparkSession.builder.appName(\"BigData-Challenge\").config(\"spark.driver.extraClassPath\",\"/content/postgresql-42.2.16.jar\").getOrCreate()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "4214464d",
   "metadata": {},
   "source": [
    "# Load Amazon Data into Spark DataFrame"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "7704d651",
   "metadata": {},
   "outputs": [
    {
     "ename": "NameError",
     "evalue": "name 'spark' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mNameError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[0;32m/var/folders/17/2bx63dk94yxghdn6klt09vt80000gn/T/ipykernel_94707/1120264123.py\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[0;32mfrom\u001b[0m \u001b[0mpyspark\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mSparkFiles\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      2\u001b[0m \u001b[0murl\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;34m\"https://s3.amazonaws.com/amazon-reviews-pds/tsv/amazon_reviews_us_Digital_Video_Games_v1_00.tsv.gz\"\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 3\u001b[0;31m \u001b[0mspark\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0msparkContext\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0maddFile\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0murl\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      4\u001b[0m \u001b[0mdf\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mspark\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mread\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0moption\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"encoding\"\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m\"UTF-8\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mcsv\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mSparkFiles\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mget\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"amazon_reviews_us_Digital_Video_Games_v1_00.tsv.gz\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0msep\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m\"\\t\"\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mheader\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;32mTrue\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0minferSchema\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;32mTrue\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      5\u001b[0m \u001b[0mdf\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mshow\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mNameError\u001b[0m: name 'spark' is not defined"
     ]
    }
   ],
   "source": [
    "from pyspark import SparkFiles\n",
    "url = \"https://s3.amazonaws.com/amazon-reviews-pds/tsv/amazon_reviews_us_Digital_Video_Games_v1_00.tsv.gz\"\n",
    "spark.sparkContext.addFile(url)\n",
    "df = spark.read.option(\"encoding\", \"UTF-8\").csv(SparkFiles.get(\"amazon_reviews_us_Digital_Video_Games_v1_00.tsv.gz\"), sep=\"\\t\", header=True, inferSchema=True)\n",
    "df.show()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "6023306a",
   "metadata": {},
   "source": [
    "# Create DataFrames to match tables"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "548bd55b",
   "metadata": {},
   "outputs": [],
   "source": [
    "from pyspark.sql.functions import to_date\n",
    "# Read in the Review dataset as a DataFrame"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "1c778056",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Create the customers_table DataFrame\n",
    "customers_df = df.groupby(\"customer_id\").agg({'customer_id': 'count'}).withColumnRenamed(\"count(customer_id)\", \"customer_count\")\n",
    "customers_df.show(10)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "df35b03f",
   "metadata": {},
   "outputs": [],
   "source": [
    "customers_df.count()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "16af1b22",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Create the products_table DataFrame and drop duplicates. \n",
    "products_df = df.select(['product_id', 'product_title']).drop_duplicates(['product_id'])\n",
    "products_df.show(10)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "d4227127",
   "metadata": {},
   "outputs": [],
   "source": [
    "products_df.count()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "7b5da1f5",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Create the review_id_table DataFrame. \n",
    "review_id_df = df.select(['review_id','customer_id','product_id', 'product_parent', to_date(\"review_date\", 'yyyy-MM-dd').alias(\"review_date\")])\n",
    "review_id_df.show(10)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e53e86bf",
   "metadata": {},
   "outputs": [],
   "source": [
    "review_id_df.count()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "29ccb020",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Create the vine_table DataFrame\n",
    "vine_df = df.select(['review_id', 'star_rating','helpful_votes', 'total_votes', 'vine', 'verified_purchase'])\n",
    "vine_df.show(10)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "27ca7710",
   "metadata": {},
   "source": [
    "# Connect to the AWS RDS instance and write each DataFrame to its table."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "0bdaabf4",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Configure settings for RDS\n",
    "mode = \"append\"\n",
    "# jdbc_url=\"jdbc:postgresql://amazon-reviews.camjftkrswax.us-east-1.rds.amazonaws.com:5432/postgres\"\n",
    "jdbc_url=\"jdbc:postgresql://dataviz.camjftkrswax.us-east-1.rds.amazonaws.com:5432/postgres\"\n",
    "config = {\"user\":\"postgres\", \n",
    "          \"password\": \"\", \n",
    "          \"driver\":\"org.postgresql.Driver\"}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a8984489",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Write review_id_df to table in RDS\n",
    "review_id_df.write.jdbc(url=jdbc_url, table='review_id_table', mode=mode, properties=config)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f61dbfe7",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Write products_df to table in RDS\n",
    "# about 3 min\n",
    "products_df.write.jdbc(url=jdbc_url, table='products_table', mode=mode, properties=config)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "77291331",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Write customers_df to table in RDS\n",
    "# 5 min 14 s\n",
    "customers_df.write.jdbc(url=jdbc_url, table='customers_table', mode=mode, properties=config)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "53ffa013",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Write vine_df to table in RDS\n",
    "# 11 minutes\n",
    "vine_df.write.jdbc(url=jdbc_url, table='vine_table', mode=mode, properties=config)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f63ea428",
   "metadata": {},
   "outputs": [],
   "source": [
    "# -- inside of pgAdmin\n",
    "# -- Query database to check successful upload\n",
    "# SELECT * FROM customers_table;\n",
    "# SELECT * FROM products_table;\n",
    "# SELECT * FROM review_id_table;\n",
    "# SELECT * FROM vine_table;"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "PythonData",
   "language": "python",
   "name": "pythondata"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
